#CORES UTILIZADAS
VERMELHO_PADRAO = [246, 19, 23]
AZUL_PADRAO = [89, 197, 207]
BRANCO = 255
PRETO = 0
CINZA = 128
FUNDO_TEXTO_ITENS = 220
FUNDO_APP_PRINCIPAL_HEADER = "#59C5CF"
FUNDO_APP_PRINCIPAL_HEADER_SELECAO = "lightblue"

#ACESSO AO DB
MDB = r'\\LTC-SV\G & M Systens\PRINCIPAL.MDB'  #r'C:\Users\LTC\Desktop\gabe\PY\DBPARATESTE.MDB'
DRV = '{Microsoft Access Driver (*.mdb, *.accdb)}'
CONN_STR = ';'.join(['DRIVER=' + DRV, 'DBQ=' + MDB])
